"""Initial migration

Revision ID: 04037b890de3
Revises: d79000d6ee12
Create Date: 2024-07-12 19:49:36.872379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04037b890de3'
down_revision = 'd79000d6ee12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Api_Username', sa.String(length=512), nullable=True))
        batch_op.drop_column('api_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_secret', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_column('Api_Username')

    # ### end Alembic commands ###
