"""empty message

Revision ID: 5eef3c5c16f6
Revises: b43075801a24
Create Date: 2024-07-10 11:32:10.264442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5eef3c5c16f6'
down_revision = 'b43075801a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_active_plan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plan_valid_until', sa.DateTime(), nullable=True))
        batch_op.drop_column('subscription_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('plan_valid_until')
        batch_op.drop_column('has_active_plan')

    # ### end Alembic commands ###
