"""Add credit column to user table

Revision ID: 61dfb2ab3713
Revises: f809b452fc4a
Create Date: 2024-07-14 19:33:07.114366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dfb2ab3713'
down_revision = 'f809b452fc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referred_by')
        batch_op.drop_column('credit')

    # ### end Alembic commands ###
