"""Initial migration

Revision ID: d79000d6ee12
Revises: 85f0875bfdfa
Create Date: 2024-07-12 19:33:08.408689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79000d6ee12'
down_revision = '85f0875bfdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('pin')
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
