"""Initial migration

Revision ID: f809b452fc4a
Revises: 04037b890de3
Create Date: 2024-07-12 20:34:35.404369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f809b452fc4a'
down_revision = '04037b890de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_token', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('feed_token', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('feed_token')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('auth_token')

    # ### end Alembic commands ###
